#========================================
# Test profile settings (IT tests)
#========================================

jwt:
  secret: dGVzdFNlY3JldEtleUZvclRlc3RpbmdQdXJwb3Nlc09ubHkxMg==

spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.14:///
  flyway:
    enabled: true

  security:
    oauth2:
      client:
        provider:
          sms-sender:
            token-uri: http://localhost:${wiremock.server.port}/token
          teams-sender:
            token-uri: http://localhost:${wiremock.server.port}/token
        registration:
          sms-sender:
            client-id: the-client-id
            client-secret: the-client-secret
          teams-sender:
            client-id: the-client-id
            client-secret: the-client-secret

integration:
  sms-sender:
    base-url: http://localhost:${wiremock.server.port}/sms-sender
  teams-sender:
    base-url: http://localhost:${wiremock.server.port}/teams-sender
